=== marvellouz/fmi_projects/XML/movies.dtd
<!ELEMENT Body (Movies, Actors)>
<!ELEMENT Movies (Movie+)>
<!ELEMENT Movie (Title, Year, Picture, Genres, Keywords, Tagline, Plot, Directors, Writers, Characters)>
  <!ATTLIST Movie MovieId ID #REQUIRED
                  Length CDATA "0"
                  Color (yes|no) #IMPLIED
                  Actors IDREFS #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Picture (#PCDATA)>
<!ELEMENT Genres (Genre+)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Tagline (#PCDATA)>
<!ELEMENT Plot (#PCDATA)>
<!ELEMENT Keywords (Keyword+)>
  <!ELEMENT Keyword (#PCDATA)>
<!ELEMENT Directors (Director+)>
  <!ELEMENT Writers (Writer+)>
<!ELEMENT Director (Name)>
<!ELEMENT Writer (Name)>
<!ELEMENT Characters (Character+)>
  <!ELEMENT Character (#PCDATA)>
    <!ATTLIST  Character Actor IDREF #REQUIRED>
<!ELEMENT Actors (Actor+)>
  <!ELEMENT Actor (Name, Biography, Awards)>
    <!ATTLIST Actor ActorId ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Biography (#PCDATA)>
<!ELEMENT Awards (#PCDATA)>

=== marvellouz/fmi_projects/XML/movies_incorrect_2.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE Body SYSTEM "movies.dtd">

<Body>
  <Movies>
    <Movie MovieId = "sr" Length = "185" Color = "yes" Actors = "rdn jf ab">
      <Title>Taxi Driver</Title>
      <Year>1976</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTAzNzY1NzYzMzFeQTJeQWpwZ15BbWU3MDc3MjA0NTE@._V1._SX99_SY140_.jpg
      </Picture>

      <Genres>
        <Genre>Drama</Genre>
        <Genre>Thriller</Genre>
      </Genres>

      <Keywords>
        <Keyword>New York City</Keyword>
        <Keyword>Taxi Driver</Keyword>
        <Keyword>Date</Keyword>
      </Keywords>
      <Tagline>On every street in every city, there's a nobody who dreams of being a somebody. </Tagline>

      <Plot>
        A mentally unstable Vietnam war veteran works as nighttime taxi driver in a city whose perceived decadence and sleaze feeds his urge to violently lash out, attempting to save a teenage prostitute in the process.
      </Plot>

      <Directors>
        <!--В <Director> има два пъти <Name>, а трябва да се среща само веднъж. Ако има повече от един режисьора, трябра да са в отделен таг <Director>. Освен това няма дефиниран атрибут Married в DTD файла. -->
        <Director>
          <Name Married = "Yes">Martin Scorsese</Name>
          <Name>Paul Vega</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Paul Schrader</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "rdn">Travis Bickle</Character>
        <Character Actor = "jf">Iris</Character>
        <Character Actor = "ab">Tom</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "pf" Length = "184" Color = "yes" Actors = "jt sj ut">
      <Title>Pulp Fiction</Title>
      <Year>1994</Year>

      <Picture>
        http://www.imdb.com/rg/action-box-title/primary-photo/media/rm3216480512/tt0110912
      </Picture>

      <Genres>
        <Genre>Crime</Genre>
        <Genre>Thriller</Genre>
      </Genres>

      <Keywords>
        <Keyword>Boxer</Keyword>
        <Keyword>Restaurant</Keyword>
        <Keyword>Diner</Keyword>
      </Keywords>
      <Tagline>Girls like me don't make invitations like this to just anyone! </Tagline>

      <Plot>
        The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.
      </Plot>

      <Directors>

        <Director>
          <Name>Quentin Tarantino</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Quentin Tarantino</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "jt">Vincent Vega</Character>
        <Character Actor = "sj">Jules Winnfield</Character>
        <Character Actor = "ut">Mia Wallace</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "bc" Length = "199" Color = "yes" Actors = "jt ut vv">
      <Title>Be Cool</Title>
      <Year>2005</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTQ4NTI2NTg1MF5BMl5BanBnXkFtZTcwMzkxOTgyMQ@@._V1._SX100_SY136_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Crime</Genre>
      </Genres>

      <Keywords>
        <Keyword>Sequel</Keyword>
        <Keyword>Music Business</Keyword>
        <Keyword>Russian Mafia</Keyword>
      </Keywords>
      <Tagline> Everyone is looking for the next big hit </Tagline>

      <Plot>
        Disenchanted with the movie industry, Chili Palmer (John Travolta) tries the music industry, meeting and romancing a widow of a music exec (Uma Thurman) on the way.
      </Plot>

      <Directors>

        <Director>
          <Name>F. Gary Gray</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Elmore Leonard</Name>
        </Writer>

        <Writer>
          <Name>Peter Steinfeld</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "jt">Chili Palmer</Character>
        <Character Actor = "ut">Edie Athens</Character>
        <Character Actor = "vv">Raji</Character>
      </Characters>
    </Movie>
  </Movies>

  <Actors>
    <Actor ActorId = "rdn">
      <Name>Robert De Niro</Name>
      <Biography>Robert De Niro, who is thought of as one of the greatest actors of his time, was born in New York City in 1943 to two artists. He was trained at the Stella Adler Conservatory and the American Workshop. He first gained fame for his role in Bang the Drum Slowly (1973), but he gained his reputation as a volatile actor in Mean Streets (1973), which was his first film with director Martin Scorsese. In 1974 De Niro received an Academy Award for best supporting actor for his role in The Godfather: Part II (1974) and received Academy Award nomations for best actor in Taxi Driver (1976), The Deer Hunter (1978), and Cape Fear (1991). </Biography>
      <Awards>Won 2 Oscars. Another 28 wins and 34 nominations </Awards>
    </Actor>

    <Actor ActorId = "jf">
      <Name>Jodie Foster</Name>
      <Biography>Alicia Christian Foster was born on November 19, 1962, in Los Angeles.</Biography>
      <Awards>Won 2 Oscars. Another 36 wins and 20 nominations </Awards>
    </Actor>

    <Actor ActorId = "ab">
      <Name>Albert Brooks</Name>
      <Biography>Born in 22 July 1947, Beverly Hills, California, USA</Biography>
      <Awards>Nominated for Oscar. Another 6 wins and 1 nomination </Awards>

    </Actor>
    <Actor ActorId = "jt">
      <Name>John Travolta</Name>
      <Biography>John Travolta first gained fame as the swaggering Vinnie Barbarino on the television series "Welcome Back, Kotter" (1975). In 1977, he parlayed his teeny-bopper fame into a big-screen career with the disco blockbuster Saturday Night Fever (1977). He languished in light dramas and television movies in the 1980s, but started a comeback in 1989 with Look Who's Talking (1989). </Biography>
      <Awards>Nominated for 2 Oscars. Another 30 wins and 28 nominations</Awards>
    </Actor>

    <Actor ActorId = "sj">
      <Name>Samuel L. Jackson  </Name>
      <Biography>Samuel L. Jackson usually played bad guys and drug addicts before becoming an action hero, as the character Mitch Henessey, in The Long Kiss Goodnight (1996) and in Die Hard: With a Vengeance (1995). From character player to leading man. His performance in Pulp Fiction (1994) gave him an Oscar nomination for his character Jules Winnfield. </Biography>
      <Awards>Nominated for Oscar. Another 17 wins and 34 nominations</Awards>
    </Actor>
    <Actor ActorId = "ut">
      <Name>Uma Thurman</Name>
      <Biography>Uma Karuna Thurman, daughter of Robert Thurman and Nena Thurman, was born in Boston, Massachusetts, on April 29, 1970. Uma grew up in Amherst, Massachusetts, where her father worked at Amherst College. She left boarding school at just 15, already determined to become an actress. She moved to New York to follow her dream.</Biography>
      <Awards>Nominated for Oscar. Another 11 wins and 29 nominations</Awards>
    </Actor>

  <Actor ActorId = "vv">
    <Name>Vince Vaughn</Name>
    <Biography>Vincent Anthony Vaughn was born on March 28, 1970, in Minneapolis, Minnesota, USA and raised in Lake Forest, Illinois, USA.</Biography>
    <Awards>5 wins and 8 nominations </Awards>
  </Actor>

</Actors>
</Body>

=== marvellouz/fmi_projects/XML/movies_2.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE Body SYSTEM "movies.dtd">

<Body>
  <Movies>
    <Movie MovieId = "cl" Length = "195" Color = "no" Actors = "cc vc fl">
      <Title>City Lights</Title>
      <Year>1931</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTk3Nzg1MTcxN15BMl5BanBnXkFtZTcwNjg5MDU5Mg@@._V1._SX100_SY134_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Tramp</Keyword>
        <Keyword>Operation</Keyword>
        <Keyword>Little Tramp</Keyword>
      </Keywords>
      <Tagline>The Tramp struggles to help a blind flower girl he has fallen in love with.</Tagline>

      <Plot>
        A tramp falls in love with a beautiful blind girl. Her family is in financial trouble. The tramp's on-and-off friendship with a wealthy man allows him to be the girl's benefactor and suitor.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>
      </Writers>

      <Characters>
        <Character Actor = "cc">A Tramp</Character>
        <Character Actor = "vc">A Blind Girl</Character>
        <Character Actor = "fl">The Blind Girl's Grandmother</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "mt" Length = "184" Color = "no" Actors = "cc pg hb">
      <Title>Modern Times</Title>
      <Year>1936</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMjE0NDM4NDcyOF5BMl5BanBnXkFtZTcwNjc1MTAwMQ@@._V1._SX100_SY134_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Machine</Keyword>
        <Keyword>Invention</Keyword>
        <Keyword>Tramp</Keyword>
      </Keywords>
      <Tagline>He stands alone as the greatest entertainer of modern times! No one on earth can make you laugh as heartily or touch your heart as deeply...the whole world laughs, cries and thrills to his priceless genius!</Tagline>

      <Plot>
        Chaplins last 'silent' film, filled with sound effects, was made when everyone else was making talkies. Charlie turns against modern society, the machine age, (The use of sound in films ?) and progress. Firstly we see him frantically trying to keep up with a production line, tightening bolts. He is selected for an experiment with an automatic feeding machine, but various mishaps leads his boss to believe he has gone mad, and Charlie is sent to a mental hospital... When he gets out, he is mistaken for a communist while waving a red flag, sent to jail, foils a jailbreak, and is let out again. We follow Charlie through many more escapades before the film is out.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "cc">A Factory Worker</Character>
        <Character Actor = "pg">A Gamin</Character>
        <Character Actor = "hb">Cafe Proprietor</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "tgd" Length = "199" Color = "no" Actors = "cc jo rg">
      <Title>The Great Dictator</Title>
      <Year>1940</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMjE1OTI0MDU0N15BMl5BanBnXkFtZTcwMTc1MTAwMQ@@._V1._SX100_SY133_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
        <Genre>War</Genre>
      </Genres>

      <Keywords>
        <Keyword>Barber</Keyword>
        <Keyword>Dictator</Keyword>
        <Keyword>Soldier</Keyword>
      </Keywords>
      <Tagline>The Comedy Masterpiece!</Tagline>

      <Plot>
        In Chaplin's satire on Nazi Germany, dictator Adenoid Hynkel has a double... a poor Jewish barber... who one day is mistaken for Hynkel.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "cc">Hynkel - Dictator of Tomania / A Jewish Barber</Character>
        <Character Actor = "jo">Napaloni - Dictator of Bacteria</Character>
        <Character Actor = "rg">Schultz</Character>
      </Characters>
    </Movie>
  </Movies>

  <Actors>
    <Actor ActorId = "cc">
      <Name>Charles Chaplin</Name>
      <Biography>His first movie was Making a Living (1914); however, his next film, Kid Auto Races at Venice (1914), was destined to change his entire career. This picture saw him wearing baggy pants borrowed from 'Roscoe 'Fatty' Arbuckle', size 14 shoes belonging to Ford Sterling (and worn upside down to keep them from falling off), a tiny jacket from Keystone Kop Charles Avery, a bowler hat belonging to Arbuckle's father-in-law and Mack Swain's mustache trimmed down to toothbrush size.</Biography>
      <Awards>Won Oscar. Another 17 wins and 3 nominations</Awards>
    </Actor>

    <Actor ActorId = "vc">
      <Name>Virginia Cherrill</Name>
      <Biography>Actress in US and UK films of the early 1930s. Born on a farm, Cherrill.</Biography>
      <Awards>1 win</Awards>
    </Actor>

    <Actor ActorId = "fl">
      <Name>Florence Lee</Name>
      <Biography>Borb on 1 September 1962, Hollywood, California, USA.</Biography>
      <Awards>No awards</Awards>

    </Actor>
    <Actor ActorId = "pg">
      <Name>Paulette Goddard</Name>
      <Biography>Pauline Marion Goddard Levy was born in Whitestone Landing, New York</Biography>
      <Awards>Nominated for Oscar. Another 1 win</Awards>
    </Actor>

    <Actor ActorId = "hb">
      <Name>Henry Bergman</Name>
      <Biography>Comic actor from silents who later assisted Chaplin in directing.</Biography>
      <Awards>No awards</Awards>
    </Actor>
    <Actor ActorId = "jo">
      <Name>Jack Oakie</Name>
      <Biography>Born in 23 January 1978, Los Angeles, California, USA</Biography>
      <Awards>Nominated for Oscar. Another 1 win</Awards>
    </Actor>

  <Actor ActorId = "rg">
    <Name>Reginald Gardiner</Name>
    <Biography>Born in 7 July 1980, Westwood, California, USA</Biography>
    <Awards>No awards</Awards>
  </Actor>

</Actors>
</Body>

=== marvellouz/fmi_projects/XML/movies_3.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE Body SYSTEM "movies.dtd">

<Body>
  <Movies>
    <Movie MovieId = "sl" Length = "195" Color = "yes" Actors = "ln bk rf">
      <Title>Schindler's List</Title>
      <Year>1993</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTIxOTAxNTc4NF5BMl5BanBnXkFtZTcwOTg1NzQyMQ@@._V1._SX97_SY140_.jpg
      </Picture>

      <Genres>
        <Genre>Biography</Genre>
        <Genre>Drama</Genre>
        <Genre>History</Genre>
      </Genres>

      <Keywords>
        <Keyword>Factory</Keyword>
        <Keyword>Businessman</Keyword>
        <Keyword>Death</Keyword>
        <Keyword>Jewish</Keyword>
        <Keyword>Holocaust </Keyword>
      </Keywords>
      <Tagline>Whoever saves one life, saves the world entire.</Tagline>

      <Plot>
        Oskar Schindler uses Jews to start a factory in Poland during the war. He witnesses the horrors endured by the Jews, and starts to save them.
      </Plot>

      <Directors>

        <Director>
          <Name>Steven Spielberg</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Thomas Keneally</Name>
        </Writer>

        <Writer>
          <Name>Steven Zaillian</Name>
        </Writer>
      </Writers>

      <Characters>
        <Character Actor = "ln">Oskar Schindler</Character>
        <Character Actor = "bk">Itzhak Stern</Character>
        <Character Actor = "rf">Amon Goeth</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "segisdo" Length = "184" Color = "yes" Actors = "mm cl ap">
      <Title>Svetat e golyam i spasenie debne otvsyakade</Title>
      <Year>2008</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTk5ODQwNzE2OF5BMl5BanBnXkFtZTcwMzE0NjUxMw@@._V1._SX99_SY140_.jpg
      </Picture>

      <Genres>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Dice</Keyword>
        <Keyword>Amnesia</Keyword>
        <Keyword>Car Accident</Keyword>
      </Keywords>
      <Tagline>Journey in search of his real self</Tagline>

      <Plot>
        The story of Alex, who, with the help of his charismatic grandfather, Bai Dan, embarks on a journey in search of his real self.
      </Plot>

      <Directors>

        <Director>
          <Name>Stephan Komandarev</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Yurii Dachev</Name>
        </Writer>

        <Writer>
          <Name>Stephan Komandarev</Name>
        </Writer>
      </Writers>

      <Characters>
        <Character Actor = "mm">Bai Dan</Character>
        <Character Actor = "cl">Aleksander 'Sashko' Georgiev</Character>
        <Character Actor = "ap">Yana Georgieva</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "up" Length = "199" Color = "yes" Actors = "ea cp bp">
      <Title>Up</Title>
      <Year>2009</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTMwODg0NDY1Nl5BMl5BanBnXkFtZTcwMjkwNTgyMg@@._V1._SX94_SY140_.jpg
      </Picture>

      <Genres>
        <Genre>Animation</Genre>
        <Genre>Adventure</Genre>
        <Genre>Comedy</Genre>
      </Genres>

      <Keywords>
        <Keyword>Balloon</Keyword>
        <Keyword>Stowaway</Keyword>
        <Keyword>Dog</Keyword>
      </Keywords>
      <Tagline>Pixar's second most commercially successful film, after Finding Nemo.</Tagline>

      <Plot>
        By tying thousands of balloon to his home, 78-year-old Carl Fredricksen sets out to fulfill his lifelong dream to see the wilds of South America. Right after lifting off, however, he learns he isn't alone on his journey, since Russell, a wilderness explorer 70 years his junior, has inadvertently become a stowaway on the trip.
      </Plot>

      <Directors>

        <Director>
          <Name>Pete Docter</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Pete Docter</Name>
        </Writer>

        <Writer>
          <Name>Bob Peterson</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "ea">Carl Fredricksen</Character>
        <Character Actor = "cp">Charles Muntz</Character>
        <Character Actor = "bp">Dug / Alpha</Character>
      </Characters>
    </Movie>
  </Movies>

  <Actors>
    <Actor ActorId = "ln">
      <Name>Liam Neeson</Name>
      <Biography>Born in Northern Ireland, UK, Neeson worked as a forklift operator for Guinness... </Biography>
      <Awards>Nominated for Oscar. Another 8 wins and 15 nominations</Awards>
    </Actor>

    <Actor ActorId = "bk">
      <Name>Ben Kingsley</Name>
      <Biography>31 December 1943, Scarborough, Yorkshire, England, UK</Biography>
      <Awards>Won Oscar. Another 29 wins and 36 nominations</Awards>
    </Actor>

    <Actor ActorId = "rf">
      <Name>Ralph Fiennes</Name>
      <Biography>Eldest of 6 children born to photographer Mark Fiennes and his wife, Jini - aka Jennifer Lash - a novelist.</Biography>
      <Awards>Nominated for 2 Oscars. Another 13 wins and 30 nominations</Awards>

    </Actor>
    <Actor ActorId = "mm">
      <Name>Miki Manojlovic</Name>
      <Biography>5 April 1950, Belgrade, Yugoslavia</Biography>
      <Awards>1 nomination</Awards>
    </Actor>

    <Actor ActorId = "cl">
      <Name>Carlo Ljubek</Name>
      <Biography>21 May 1976, Bocholt, Germany</Biography>
      <Awards>No awards</Awards>
    </Actor>
    <Actor ActorId = "ap">
      <Name>Ana Papadopulu</Name>
      <Biography>Born in 31 december 1978 Sofia.</Biography>
      <Awards>No awards</Awards>
    </Actor>

  <Actor ActorId = "ea">
    <Name>Edward Asner</Name>
    <Biography>Born in 15 November 1929, Kansas City, Kansas, USA</Biography>
    <Awards>Won 5 Golden Globes. Another 13 wins and 20 nominations</Awards>
  </Actor>

  <Actor ActorId = "cp">
    <Name>Christopher Plummer</Name>
    <Biography>Christopher Plummer is arguably the finest actor of the post-World War II period never to be nominated for an Academy Award, following in the footsteps of John Barrymore, for whose portrayal on Broadway he won a Tony Award. Aside from Barrymore, Plummer is the premier Shakespearean actor to come out of North America in the 20th century. He has also given many fine portrayals on film, particularly as he got older and settled down into a comfortable marriage with his third wife. Though he likely always be remembered as "Baron Von Trapp" in the atomic bomb-strength blockbuster The Sound of Music (1965) (a film he continues to despise), his later film work includes such outstanding performances as the best cinema Sherlock Holmes--other than Basil Rathbone -- in Murder by Decree (1979), the chilling villain in The Silent Partner (1978), his iconoclastic Mike Wallace in The Insider (1999) and the empathetic psychiatrist in A Beautiful Mind (2001). </Biography>
    <Awards>Nominated for 2 Golden Globes. Another 11 wins and 21 nominations </Awards>
  </Actor>
  <Actor ActorId = "bp">
    <Name>Bob Peterson</Name>
    <Biography>Bob Peterson was born in Wooster, Ohio, USA, in 1961. He studied mechanical engineering at Ohio Northern University, where he took computer graphics courses and graduated in 1983. He continued his studies in mechanical engineering at Purdue University where he earned a master's degree in 1986. While a student, he wrote and drew a cartoon strip called "Loco Motive." Before joining Pixar in 1994, he worked at Wavefront Technologies, Inc. and Rez-n-8 Productions.</Biography>
    <Awards>Nominated for Oscar. Another 2 wins and 13 nominations</Awards>
  </Actor>
</Actors>
</Body>

=== marvellouz/fmi_projects/XML/movies_4.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE Body SYSTEM "movies.dtd">

<Body>
  <Movies>
    <Movie MovieId = "l" Length = "90" Color = "no" Actors = "cc vc fl">
      <Title>Limelight</Title>
      <Year>1952</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTU2MTk0MzE3MV5BMl5BanBnXkFtZTcwMDc1MTAwMQ@@._V1._SX100_SY133_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Ballet</Keyword>
        <Keyword>Ballet Dancer</Keyword>
        <Keyword>Hope</Keyword>
      </Keywords>
      <Tagline>A story of a ballerina and a clown</Tagline>

      <Plot>
        A fading comedian and a suicidally despondent ballet dancer must look to each other to find meaning and hope in their lives.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>
      </Writers>

      <Characters>
        <Character Actor = "cc">Calvero</Character>
        <Character Actor = "vc">Terry, a Dancer</Character>
        <Character Actor = "fl">Neville</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "tk" Length = "84" Color = "no" Actors = "cc pg hb">
      <Title>The Kid</Title>
      <Year>1921</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMTI3OTgxMDI3Nl5BMl5BanBnXkFtZTcwMzUwMjUyMQ@@._V1._SX100_SY115_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Orphan</Keyword>
        <Keyword>Broken Window</Keyword>
        <Keyword>Angel</Keyword>
      </Keywords>
      <Tagline>This is the great film he has been working on for a whole year </Tagline>

      <Plot>
        The Tramp cares for an abandoned child, but events put that relationship in jeopardy.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "cc">A Tramp</Character>
        <Character Actor = "pg">The Woman</Character>
        <Character Actor = "hb">The Kid</Character>
      </Characters>
    </Movie>

    <Movie MovieId = "mv" Length = "89" Color = "no" Actors = "cc jo rg">
      <Title>Monsieur Verdoux</Title>
      <Year>1947</Year>

      <Picture>
        http://ia.media-imdb.com/images/M/MV5BMjE5ODU3MDk4N15BMl5BanBnXkFtZTcwNTAxMjUyMQ@@._V1._SX100_SY117_.jpg
      </Picture>

      <Genres>
        <Genre>Comedy</Genre>
        <Genre>Drama</Genre>
      </Genres>

      <Keywords>
        <Keyword>Marriage</Keyword>
        <Keyword>Socialite</Keyword>
        <Keyword>Music Score Composed By Director</Keyword>
      </Keywords>
      <Tagline> Chaplin's Bluebeard comedy is a killer! </Tagline>

      <Plot>
        A suave but cynical man supports his family by marrying and murdering rich women for their money, but the job has some occupational hazards.
      </Plot>

      <Directors>

        <Director>
          <Name>Charles Chaplin</Name>
        </Director>
      </Directors>

      <Writers>

        <Writer>
          <Name>Charles Chaplin</Name>
        </Writer>

      </Writers>

      <Characters>
        <Character Actor = "cc">Henri Verdoux</Character>
        <Character Actor = "jo">Peter Verdoux</Character>
        <Character Actor = "rg">Maurice Bottello</Character>
      </Characters>
    </Movie>
  </Movies>

  <Actors>
    <Actor ActorId = "cc">
      <Name>Charles Chaplin</Name>
      <Biography>His first movie was Making a Living (1914); however, his next film, Kid Auto Races at Venice (1914), was destined to change his entire career. This picture saw him wearing baggy pants borrowed from 'Roscoe 'Fatty' Arbuckle', size 14 shoes belonging to Ford Sterling (and worn upside down to keep them from falling off), a tiny jacket from Keystone Kop Charles Avery, a bowler hat belonging to Arbuckle's father-in-law and Mack Swain's mustache trimmed down to toothbrush size.</Biography>
      <Awards>Won Oscar. Another 17 wins and 3 nominations</Awards>
    </Actor>

    <Actor ActorId = "vc">
      <Name>Virginia Cherrill</Name>
      <Biography>Actress in US and UK films of the early 1930s. Born on a farm, Cherrill.</Biography>
      <Awards>1 win</Awards>
    </Actor>

    <Actor ActorId = "fl">
      <Name>Florence Lee</Name>
      <Biography>Borb on 1 September 1962, Hollywood, California, USA.</Biography>
      <Awards>No awards</Awards>

    </Actor>
    <Actor ActorId = "pg">
      <Name>Paulette Goddard</Name>
      <Biography>Pauline Marion Goddard Levy was born in Whitestone Landing, New York</Biography>
      <Awards>Nominated for Oscar. Another 1 win</Awards>
    </Actor>

    <Actor ActorId = "hb">
      <Name>Henry Bergman</Name>
      <Biography>Comic actor from silents who later assisted Chaplin in directing.</Biography>
      <Awards>No awards</Awards>
    </Actor>
    <Actor ActorId = "jo">
      <Name>Jack Oakie</Name>
      <Biography>Born in 23 January 1978, Los Angeles, California, USA</Biography>
      <Awards>Nominated for Oscar. Another 1 win</Awards>
    </Actor>

  <Actor ActorId = "rg">
    <Name>Reginald Gardiner</Name>
    <Biography>Born in 7 July 1980, Westwood, California, USA</Biography>
    <Awards>No awards</Awards>
  </Actor>

</Actors>
</Body>
